version: '3.8'
services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    volumes:
        - './mosquitto-data:/mosquitto'
    ports:
        - '1883:1883'
        - '9001:9001'
    command: 'mosquitto -c /mosquitto-no-auth.conf'
  z2m:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
        - ./z2m-data:/app/data
        - /run/udev:/run/udev:ro
    ports:
        - 8081:8081
    environment:
       - TZ=Australia/Brisane
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_d80fe62d653aef11a73c321455516304-if00-port0:/dev/ttyUSB0:rwm
    group_add:
      - 27 # dialout
      - 3 # tty
      - 19 # uucp
